import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FileIcon } from "lucide-react";
import SideBar from "./side-nav";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="conatiner mx-auto pt-4 px-2">
      <div className="flex gap-8">
        <SideBar />
        <div className="w-full ">{children}</div>
      </div>
    </main>
  );
}
